# Generated by Django 3.2.7 on 2021-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/deafult.png', upload_to='images/'),
        ),
    ]
